/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as HouseholdsIndexRouteImport } from './routes/households/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as HouseholdsHouseholdNameApplianceNameRouteImport } from './routes/households/$householdName.$applianceName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIndexRoute = HouseholdsIndexRouteImport.update({
  id: '/households/',
  path: '/households/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsHouseholdNameApplianceNameRoute =
  HouseholdsHouseholdNameApplianceNameRouteImport.update({
    id: '/households/$householdName/$applianceName',
    path: '/households/$householdName/$applianceName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/config/': typeof ConfigIndexRoute
  '/households/': typeof HouseholdsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/households/$householdName/$applianceName': typeof HouseholdsHouseholdNameApplianceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/config': typeof ConfigIndexRoute
  '/households': typeof HouseholdsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/households/$householdName/$applianceName': typeof HouseholdsHouseholdNameApplianceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/config/': typeof ConfigIndexRoute
  '/households/': typeof HouseholdsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/households/$householdName/$applianceName': typeof HouseholdsHouseholdNameApplianceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs/$runId'
    | '/config/'
    | '/households/'
    | '/runs/'
    | '/households/$householdName/$applianceName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs/$runId'
    | '/config'
    | '/households'
    | '/runs'
    | '/households/$householdName/$applianceName'
  id:
    | '__root__'
    | '/'
    | '/runs/$runId'
    | '/config/'
    | '/households/'
    | '/runs/'
    | '/households/$householdName/$applianceName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  HouseholdsIndexRoute: typeof HouseholdsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  HouseholdsHouseholdNameApplianceNameRoute: typeof HouseholdsHouseholdNameApplianceNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/': {
      id: '/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof HouseholdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$householdName/$applianceName': {
      id: '/households/$householdName/$applianceName'
      path: '/households/$householdName/$applianceName'
      fullPath: '/households/$householdName/$applianceName'
      preLoaderRoute: typeof HouseholdsHouseholdNameApplianceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  HouseholdsIndexRoute: HouseholdsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  HouseholdsHouseholdNameApplianceNameRoute:
    HouseholdsHouseholdNameApplianceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
